### ISSUE TITLE
Option 1: Task 2.4 + 2.5 Add Article Selection, Rating, and Saving Functionality to Second Page

### ISSUE THREAD

**Issue by zweahtet** [cs169/fa23-chips-10.5-1#6]
We need to add functionality to the second page of the news article creation process. After a user has selected a Representative and Issue, clicked ‘Search’, and been taken to the second page displaying the top 5 articles from the News API, they should be able to select their desired article.

Next to each article in the list, there should be a radio button. The user can select one of these radio buttons to choose which article they want to rate for the selected representative.

After selecting an article, the user should be able to rate it. This could be done through a rating input field or a rating dropdown menu.

Finally, there should be a ‘Save’ button on this page. When the user clicks this ‘Save’ button, the selected article and its rating should be added to the database.

## a lo-fi mockup
![media_1_cacc44ea2da0fde947a7301086ced57f-fad8d22004d1cca1](https://github.com/cs169/fa23-chips-10.5-1/assets/70414756/8cf983eb-5ab7-40fe-9ab0-c3606a114233)

**Comment by Alex-A-Rios** [comment]
done with task 2.4 and 2.5
